// import { createSelector, createEntityAdapter } from "@reduxjs/toolkit";
import { apiSlice } from '../../app/api/apiSlice';

// normalize data for faster lookups
// also gives us methods to manipulate normalized data 
// (addOne, addMany, setAll, removeOne, etc.)
// const todosAdapter = createEntityAdapter();

// calling getInitialState() will create the initial state object with the following structure:
// {
//   ids: [], // array of todo ids
//   entities: {} // object with todo objects keyed by id
// }
// add extra properties to the initial state object by passing an object as an argument 
// to getInitialState() (ex: { status: 'idle', error: null })
// const initialState = todosAdapter.getInitialState();

export const todoApiSlice = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    fetchTodos: builder.query({
      query: ({ userId, listId }) => ({
        url: `/users/${userId}/lists/${listId}/todos`,
        validateStatus: (response, result) => {
          // RTK Query considers a response valid if the status code is 200-299
          // and the result does not have an error property
          if (response.status === 200 && !result.error) {
            return result;
          }

          return false;
        },
      }),
      transformResponse: (responseData) => {
        // responseData is an array of todos, we want to normalize it so
        // RTK can work with it and return the normalized state object
        // we can also normalize data here without using createEntityAdapter
        // by transforming the array into an object with ids and entities properties
        // but we don't get the benefits of the pre-built reducers and selectors that come with createEntityAdapter

        // set all todos to have an id property that is equal
        // to the _id property coming from the backend (RTK query expects an id property by default, not an _id property)
        const loadedTodos = responseData.todos.map((todo) => ({
          ...todo,
          id: todo._id, // here we set id to the _id property coming from the backend
        }));

        // create the RTK query normalized structure with ids and entities properties
        const normalizedData = {
          ids: loadedTodos.map((todo) => todo.id),
          entities: loadedTodos.reduce((acc, todo) => {
            acc[todo.id] = todo;
            return acc;
          }, {}),
        };
        return normalizedData;
        // return todosAdapter.setAll(initialState, loadedTodos);
      },
      providesTags: (result, error) => {
        if (result?.ids) {
          // if we have a result with ids, we want to provide a tag for each todo and also a tag for the entire list
          return [
            { type: 'Todo', id: 'LIST' },
            ...result.ids.map((id) => ({ type: 'Todo', id })),
          ];
        }

        /* 
          if we don't have a result containing an ids property, we want to provide a tag for the 
          entire list so that it will be invalidated and refetched when a new todo is added 
        */
        return [{ type: 'Todo', id: 'LIST' }];
      },
      // keepUnusedDataFor: 5, // Cache data for 5 seconds (meaning we have to leave the component for 5 seconds before refetching data)
    }),
    addTodo: builder.mutation({
      query: ({newTodo, userId, listId}) => ({
        url: `/users/${userId}/lists/${listId}/todos`,
        method: 'POST',
        body: newTodo,
      }),
      invalidatesTags: [{ type: 'Todo', id: 'LIST' }],
    }),
    updateTodo: builder.mutation({
      query: ({ todoId, updatedFields, userId, listId }) => ({
        url: `/users/${userId}/lists/${listId}/todos/${todoId}`,
        method: 'PATCH',
        body: updatedFields,
      }),
      // the third argument to invalidatesTags is the original argument passed to the query or mutation endpoint
      // (in this case, the object containing id and updatedFields)
      // - to use the below line, we would need to normalize the data being returned from the query, this allows
      //   RTK query to manage our list of todos and merge in updates as they occur.
      invalidatesTags: (result, error, originalData) => {
        return [{ type: 'Todo', id: originalData.id }];
      },
      // invalidatesTags: [{ type: 'Todo', id: 'LIST' }],
    }),
    deleteTodo: builder.mutation({
      query: ({ todoId, userId, listId }) => ({
        url: `/users/${userId}/lists/${listId}/todos/${todoId}`,
        method: 'DELETE',
      }),
      invalidatesTags: [{ type: 'Todo', id: 'LIST' }],
    }),
  }),
});

// these hooks are auto-generated by RTK Query based on the defined endpoints
// - if its a mutation endpoint, we use `use[EndpointName]Mutation`
// - if it's a query endpoint, we use `use[EndpointName]Query`)
export const {
  useFetchTodosQuery,
  useAddTodoMutation,
  useUpdateTodoMutation,
  useDeleteTodoMutation,
} = todoApiSlice;

// returns the query result object (entire result object, not just data)
// export const selectTodosResult = todoApiSlice.endpoints.fetchTodos.select();

// creates a memoized selector
// createSelector(inputFunc, outputFunc)
// const selectTodosData = createSelector(
//   selectTodosResult,
//   (todosResult) => todosResult.data // normalized state object with ids & entities
// );

// getSelectors creates these selectors and we rename them with aliases using destructuring
// export const {
//   selectAll: selectAllTodos,
//   selectById: selectTodoById,
//   selectIds: selectTodoIds,
// } = todosAdapter.getSelectors(state => selectTodosData(state) ?? initialState);
