// import { createSelector, createEntityAdapter } from "@reduxjs/toolkit";
import { apiSlice } from '../../app/api/apiSlice';

// normalize data for faster lookups
// also gives us methods to manipulate normalized data 
// (addOne, addMany, setAll, removeOne, etc.)
// const todosAdapter = createEntityAdapter();

// calling getInitialState() will create the initial state object with the following structure:
// {
//   ids: [], // array of todo ids
//   entities: {} // object with todo objects keyed by id
// }
// add extra properties to the initial state object by passing an object as an argument 
// to getInitialState() (ex: { status: 'idle', error: null })
// const initialState = todosAdapter.getInitialState();

export const todoApiSlice = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    fetchTodos: builder.query({
      query: () => ({
        url: '/todos',
        validateStatus: (response, result) => {
          console.log('in fetchTodos.validateStatus response: ', response);
          console.log('in fetchTodos.validateStatus result: ', result);
          // RTK Query considers a response valid if the status code is 200-299 
          // and the result does not have an error property
          if (response.status === 200 && !result.error) {
            return result;
          }
          return false; 
        },
      }),
      // transformResponse: (responseData) => {
      //   // responseData is an array of todos, we want to normalize it so 
      //   // RTK can work with it and return the normalized state object
      //   const loadedUsers = responseData.map((todo) => ({
      //     ...todo,
      //     id: todo._id, // here we set id to the _id property coming from the backend
      //   }));
      //   return todosAdapter.setAll(initialState, loadedUsers);
      // },
      // providesTags: ['Todos'],
      providesTags: (result, error) => {
        if (result?.ids) {
          // if we have a result with ids, we want to provide a tag for each todo and also a tag for the entire list
          return [
            { type: 'Todo', id: 'LIST' },
            ...result.ids.map((id) => ({ type: 'Todo', id })),
          ];
        } else {
          // if we don't have a result containing an ids property, we want to provide a tag for the entire list so 
          // that it will be refetched when a new todo is added
          return [{ type: 'Todo', id: 'LIST' }];
        }
      },
      // keepUnusedDataFor: 5, // Cache data for 5 seconds (meaning we have to leave the component for 5 seconds before refetching data)
    }),
    addTodo: builder.mutation({
      query: (newTodo) => ({
        url: '/todos',
        method: 'POST',
        body: newTodo,
      }),
      // if a func is passed instead of an array, we can be more specific about which tags to invalidate
      // (ex: only invalidate the tag for the specific todo that was updated instead of all todos)
      // the func receives the result of the mutation (in this case, the new todo that was created),
      // an error if the request failed and an arg object of arguments that were passed to the mutation
      // when it was called (in this case, the newTodo data).
      // this should be based on how we are using providesTags in the fetchTodos query endpoint. 
      // If we are providing a tag for each individual todo, then we should invalidate the specific 
      // tag for each todo individually.
      invalidatesTags: [{ type: 'Todo', id: 'LIST' }],
    }),
    updateTodo: builder.mutation({
      query: ({ id, updatedFields }) => ({
        url: `/todos/${id}`,
        method: 'PATCH',
        body: updatedFields,
      }),
      invalidatesTags: [{ type: 'Todo', id: 'LIST'}],
    }),
    deleteTodo: builder.mutation({
      query: (id) => ({
        url: `/todos/${id}`,
        method: 'DELETE',
      }),
      invalidatesTags: [{ type: 'Todo', id: 'LIST'}],
    }),
  }),
});

// these hooks are auto-generated by RTK Query based on the defined endpoints
// - if its a mutation endpoint, we use `use[EndpointName]Mutation`
// - if it's a query endpoint, we use `use[EndpointName]Query`)
export const {
  useFetchTodosQuery,
  useAddTodoMutation,
  useUpdateTodoMutation,
  useDeleteTodoMutation,
} = todoApiSlice;

// returns the query result object (entire result object, not just data)
export const selectTodosResult = todoApiSlice.endpoints.fetchTodos.select();

// creates a memoized selector
// createSelector(inputFunc, outputFunc)
// const selectTodosData = createSelector(
//   selectTodosResult,
//   (todosResult) => todosResult.data // normalized state object with ids & entities
// );

// getSelectors creates these selectors and we rename them with aliases using destructuring
// export const {
//   selectAll: selectAllTodos,
//   selectById: selectTodoById,
//   selectIds: selectTodoIds,
// } = todosAdapter.getSelectors(state => selectTodosData(state) ?? initialState);
